### PR TITLE
Fixed GIS projection problem.

### PR DESCRIPTION
**Pull request by atombrella**
It looks reasonable locally. My editor removes trailing whitespace by default. My fix seems to revert the previous commit.

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks for digging into the rabbit hole.

I don't get this :) Okay of course some changes back and forth that I don't recall.

But is the fix to remove the projection that was initially added because the other x, y coordinates didn't work?

**Comment by atombrella** [comment]
Yes, and perhaps also the LatLng stuff in leaflet. I don't know. Work with it locally, and see if it makes sense there, too. The `PointField` is http://spatialreference.org/ref/epsg/wgs-84/ (SRID 4326), so I didn't understand the `transform` from another SRID.

**Comment by benjaoming** [comment]
I made your PR work with new points:

1. Using [Spatialite](https://docs.djangoproject.com/en/2.0/ref/contrib/gis/install/spatialite/)
1. Not using old data

Have to try with PostGis and to import the existing database...

**Comment by atombrella** [comment]
I don't know if you set `maxZoom` to 7 to prevent seeing the accurate address. It's changed to 12, but that was probably more to see that the points were actually at the position they were in the form.

**Comment by atombrella** [comment]
@benjaoming You gave up on testing it with PostGIS locally?

**Comment by benjaoming** [comment]
@atombrella no it seems that things are working, I stalled because I still couldn't figure out how to get the old points updated so they display at the right location.

**Comment by benjaoming** [comment]
Maybe I should just drop the :rugby_football: on preserving the old points and just wipe everything and start over :)

**Comment by benjaoming** [comment]
Seems there's a new OpenLayers widget in 2.1: https://docs.djangoproject.com/en/2.1/releases/2.1/#django-contrib-gis

**Comment by atombrella** [comment]
Upgrading to the newest Django doesn't make a big difference. I don't think it's necessary to delete the old points ...

**Comment by benjaoming** [comment]
> I don't think it's necessary to delete the old points ...

Either the old points need to be deleted or re-plotted with some transformation, and I can't figure out the right one.. The change doesn't make them appear correctly, but makes newly added points show up consistently. The code that you removed was a way to get them to show sort of correctly (but like 200 km too much North).

Well, there's not much gained in keeping them, and I don't have time to investigate what went wrong :/

**Pull request merged**
